apiVersion: v1
kind: Namespace
metadata:
  name: recoverymanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recoverymanager
  namespace: recoverymanager
  labels:
    app: recoverymanager
spec:
  selector:
    matchLabels:
      app: recoverymanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recoverymanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/recoverymanager:latest
        imagePullPolicy: Always
        name: recoverymanager
        ports:
        - containerPort: 80
          protocol: TCP
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: recoverymanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recoverymanager
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 50
